#GDAX Credentials
GDAX_API_KEY = "CHANGE_ME"
GDAX_PRIVATE_KEY = "CHANGE_ME"
GDAX_PASSPHRASE = "CHANGE_ME"

#BANDWIDTH API Credentials
BANDWIDTH_USER = "CHANGE_ME"
BANDWIDTH_TOKEN = "CHANGE_ME"
BANDWIDTH_SECRET = "CHANGE_ME"
ROOT_NUMBER = "CHANGE_ME"
ORIGIN_NUMBER = "CHANGE_ME"

#MAILGUN API Credentials
MAILGUN_API_KEY = "CHANGE_ME"
MAILGUN_API_URL = "CHANGE_ME"